name: Build HTML

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Install GMT
        run: |
          sudo apt-get install cmake libcurl4-gnutls-dev libnetcdf-dev \
                               gdal-bin libgdal-dev libfftw3-dev libpcre3-dev \
                               liblapack-dev libblas-dev libglib2.0-dev ghostscript
          source ci/install-gmt.sh
          # Add to PATH
          echo "::add-path::${GMT_INSTALL_PREFIX}/bin"
        env:
          GSHHG_VERSION : 2.3.7
          DCW_VERSION : 1.1.4
          GMT_VERSION :  6.1.0
          GMT_DOC_VERSION : 6.1
          GMT_INSTALL_PREFIX : ${{ github.workspace }}/GMT

      - name: Build documentaiton
        run: make dirhtml
